### ISSUE TITLE
Error because of invalid paths when element is hidden

### ISSUE THREAD

**Issue by Moskito89** [payw-org/squircle.js#2]
When an element is hidden, it is currently not possible to calculate the width and height. This leads to paths with the invalid string `NaN`. Is it possible to process an element only when it becomes visible? This could prevent wrong calculations.

**Comment by Moskito89** [comment]
@jhaemin Little ping. 😊

**Comment by jhaemin** [comment]
Sorry for late reply. I'll check it when I have time.
